spring:
  data:
    mongodb:
      username: root
      password: password
      host: localhost
      port: 27027
      database: notification
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: orderConfirmation:com.ecom.ecommerce.kafka.OrderConfirmation,paymentConfirmation:com.ecom.ecommerce.notification.PaymentNotificationRequest
  mail:
    host: localhost
    port: 1025
    username: ecom
    password: 781227
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040
