spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: ecom
    password: 781227
    driverClassName: org.postgresql.Driver

  jpa:
    generate-dll: true
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
        hibernate:
          format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    baseline-description: "init"
#    baseline-version: 0
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}
#    url: ${spring.datasource.url}

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8050