spring:
  config:
    import: optional:configserver:http//localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: ecom
    password: 781227
    driverClassName: org.postgresql.Driver

  jpa:
    generate-dll: true
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ecom
    password: 781227
    url: jdbc:postgresql://localhost:5432/product
  application:
    name: product-service
server:
  port: 8050