spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http//localhost:8888
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: orderConfirmation:com.ecom.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:com.ecom.ecommerce.kafka.payment.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username: ecom
    password: 781227
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
kafka:
  topic:
    payment: payment-topic
    order: order-topic
